# name: "Build image and push to official docker registry"

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-push-registry:
#     name: Build image and push to official docker registry
#     runs-on: ubuntu-latest

#     permissions:
#       contents: read
#       id-token: write
#       # Allows pushing to the GitHub Container Registry
#       packages: write

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#         with:
#           submodules: recursive

#       - name: Login to Registry
#         uses: docker/login-action@v2
#         with:
#           registry: docker.io
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Extracting package version
#         id: package_version
#         run: |
#           echo "version=v$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT

#       - name: Docker meta
#         id: docker_meta
#         uses: docker/metadata-action@v4
#         with:
#           images: minskylab/plexo-platform
#           flavor: |
#             latest=true
#           tags: |
#             type=sha,format=long,prefix=sha-
#             type=raw,value=stable,enable=${{ github.ref == 'refs/heads/main' }}
#             type=raw,value=${{ steps.package_version.outputs.version }},enable=${{ github.ref == 'refs/heads/main' }}

#       # - name: Build and push
#       #   id: docker_build
#       #   uses: docker/build-push-action@v4
#       #   with:
#       #     # cache-from: type=gha
#       #     # cache-to: type=gha,mode=max
#       #     push: true
#       #     labels: ${{ steps.docker_meta.outputs.labels }}
#       #     tags: ${{ steps.docker_meta.outputs.tags }}

#       - uses: depot/setup-action@v1

#       - name: Build and push
#         id: docker_build
#         uses: depot/build-push-action@v1
#         with:
#           project: 2hwvxx9885
#           push: true
#           labels: ${{ steps.docker_meta.outputs.labels }}
#           tags: ${{ steps.docker_meta.outputs.tags }}
